name: koompi_hotspot
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.5.0+15

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Icons & Fonts
  cupertino_icons: ^0.1.2
  flutter_launcher_icons: ^0.7.5
  font_awesome_flutter: ^8.10.0
  google_fonts: ^1.1.0
  line_icons: ^0.2.0
  line_awesome_icons: ^1.0.4+2

  # App Setting
  app_settings: ^4.0.0

  # Image & File Path
  file_picker: ^2.1.0
  flutter_image_compress: ^0.7.0
  flutter_svg: ^0.19.0
  flutter_absolute_path: ^1.0.6
  multi_image_picker: ^4.7.14
  path_provider: ^1.6.27

  # Connection & Wi-Fi
  connectivity: ^2.0.2
  data_connection_checker: ^0.3.4
  wifi_connector: ^1.0.2
  wifi_iot: ^0.3.3

  # Notification
  flutter_local_notifications: ^4.0.1+2
  awesome_notifications: ^0.0.6+9

  # Format
  date_format: ^1.0.9

  # Language
  easy_localization: ^2.1.0
  
  # Firebase
  firebase_remote_config: ^0.4.2

  # Animation
  flare_flutter: ^2.0.6
  lottie: ^0.4.1
  
  # Social
  flutter_facebook_login: ^3.0.0

  # Widget
  flutter_form_builder: ^3.14.0
  flutter_material_pickers: ^1.7.1
  fluttertoast: ^7.1.6
  google_nav_bar: ^2.0.0
  internet_speed_test: ^1.1.2+1
  intl_phone_number_input: ^0.6.0
  percent_indicator: ^2.1.9
  pin_code_fields: ^5.0.1
  rflutter_alert: ^1.1.0
  syncfusion_flutter_gauges: ^18.4.31
  groovin_widgets: ^2.0.0
  
  # Responsive
  flutter_screenutil: ^0.4.2
  responsive_framework: ^0.0.15

  # Map
  flutter_map: ^0.10.1+1
  geolocator: ^5.1.5
  location: ^2.5.4

  # Request http
  http: ^0.12.1
  jwt_decoder: ^1.0.3
  
  
  # Permission
  permission_handler: ^5.0.1+1
  package_info: ^0.4.3+2
  
  # State Management
  provider: ^4.3.2+2

  # QR
  qr_code_scanner: ^0.2.1
  qr_flutter: ^3.2.0
  
  # Storage
  shared_preferences: ^0.5.12+4
  
  # Share to other platform
  share: ^0.6.5+4

  # Shortcut
  quick_actions: ^0.4.0+10

  # Web
  flutter_webview_plugin: ^0.3.11
  url_launcher: ^5.7.10

  # On Boarding
  intro_slider: ^2.3.4
  
  # Transition Route
  page_transition: ^2.0.2

flutter_icons:
  image_path: "assets/images/Koompi-WiFi-Icon.png"
  ios: true
  android: true
  

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  country_pickers: ^2.0.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/sld_stroke.svg
    - assets/animations/
    - assets/lang/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #   - family: Schyler
  fonts:
    - family: Bold
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf

    - family: Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: CM Sans Serif
      fonts:
        - asset: assets/fonts/cm_sans_serif_2012.ttf

    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: Poppins-Light
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf

    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
