name: koompi_hotspot
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_animations: ^2.2.1
  font_awesome_flutter: ^8.8.1
  shared_preferences: ^0.5.7+3
  flutter_map: ^0.10.1
  geolocation: ^1.1.2
  flutter_screenutil: ^0.4.2
  google_nav_bar: ^2.0.0
  line_icons: ^0.2.0
  internet_speed_test: ^1.1.2+1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  google_fonts: ^1.1.0
  flutter_secure_storage: ^3.3.3
  connectivity: ^0.4.9
  flutter_launcher_icons: ^0.7.5

  cached_network_image: ^2.2.0+1
  http: ^0.12.1
  flutter_facebook_login: ^3.0.0
  sqflite: ^1.3.1
  path_provider: ^1.6.10
  postgres: ^2.1.1
  intl: ^0.16.1
  image_picker: ^0.6.7+2
  fancy_bottom_navigation: ^0.3.2
  custom_radio_grouped_button: any
  flare_flutter: any
  flutter_material_pickers: ^1.7.1

flutter_icons:
  image_path: "assets/images/koompi_logo_signal.png"
  ios: true
  android: true

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/koompi_logo.png
    - assets/images/koompi_logo_signal.png
    - assets/images/password.jpg
    - assets/images/koompi.png
    - assets/images/koompi1.jpg
    - assets/images/koompi2.jpg
    - assets/images/digital_nomad.png
    - assets/images/online_lesson.png
    - assets/images/learning.png
    - assets/images/onboarding0.png
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/image_01.png
    - assets/images/image_02.png
    - assets/animations/alert_icon.flr
    - assets/animations/koompi_splash_screen.flr
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #   - family: Schyler
  fonts:
    - family: Bold
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf

    - family: Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: CM Sans Serif
      fonts:
        - asset: assets/fonts/cm_sans_serif_2012.ttf

    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

