name: koompi_hotspot
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.3.10+14

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # animator: ^2.0.2
  app_settings: ^4.0.0
  cached_network_image: ^2.2.0+1
  # carousel_slider: ^2.3.1
  connectivity: ^2.0.2
  cupertino_icons: ^0.1.2
  data_connection_checker: ^0.3.4
  date_format: ^1.0.9
  easy_localization: ^2.1.0
  file_picker: ^2.1.0
  firebase_remote_config: ^0.4.2
  flare_flutter: ^2.0.6
  flutter_facebook_login: ^3.0.0
  flutter_form_builder: ^3.14.0
  flutter_image_compress: ^0.7.0
  flutter_launcher_icons: ^0.7.5
  flutter_map: ^0.10.1+1
  flutter_material_pickers: ^1.7.1
  flutter_screenutil: ^0.4.2
  flutter_svg: ^0.19.0
  fluttertoast: ^7.1.6
  flutter_absolute_path: ^1.0.6
  font_awesome_flutter: ^8.10.0
  getwidget: ^1.0.7
  geolocator: ^5.1.5
  google_fonts: ^1.1.0
  google_nav_bar: ^2.0.0
  http: ^0.12.1
  image_picker: ^0.6.7+17
  internet_speed_test: ^1.1.2+1
  intl: ^0.16.1
  intl_phone_number_input: ^0.6.0
  jwt_decoder: ^1.0.3
  line_icons: ^0.2.0
  location: ^2.5.4
  line_awesome_icons: ^1.0.4+2
  modal_progress_hud: ^0.1.3
  multi_image_picker: ^4.7.14
  package_info: ^0.4.3+2
  percent_indicator: ^2.1.9
  permission_handler: ^5.0.1+1
  pin_code_fields: ^5.0.1
  provider: ^4.3.2+2
  qr_code_scanner: ^0.2.1
  qr_flutter: ^3.2.0
  rflutter_alert: ^1.1.0
  shared_preferences: ^0.5.7+3
  share: ^0.6.5+4
  simply_wifi: ^1.0.5
  syncfusion_flutter_gauges: ^18.4.31
  url_launcher: ^5.7.10
  quick_actions: ^0.4.0+10
  flutter_webview_plugin: ^0.3.11
  path_provider: ^1.6.27
  share_extend: ^1.1.9
  

flutter_icons:
  image_path: "assets/images/Koompi-WiFi-Icon.png"
  ios: true
  android: true
  

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/sld_stroke.svg
    - assets/animations/
    - assets/lang/
    # - assets/images/avatar.png
    # - assets/images/koompi_logo.png
    # - assets/images/koompi_logo_signal.png
    # - assets/images/password.jpg
    # - assets/images/koompi.png
    # - assets/images/koompi1.jpg
    # - assets/images/koompi2.jpg
    # - assets/images/digital_nomad.png
    # - assets/images/online_lesson.png
    # - assets/images/learning.png
    # - assets/images/onboarding0.png
    # - assets/images/onboarding1.png
    # - assets/images/onboarding2.png
    # - assets/images/1.png
    # - assets/images/2.png
    # - assets/images/3.png
    # - assets/images/image_01.png
    # - assets/images/image_02.png
    # - assets/images/verify.png
    # - assets/animations/alert_icon.flr
    # - assets/animations/no_internet_connection.flr
    # - assets/animations/koompi_splash_screen.flr
    # - assets/animations/otp.flr
    # - assets/animations/Loading.flr
    # - assets/animations/splash_screen.flr
    # - assets/animations/lost_network.flr
    # - assets/animations/success_check.flr
    # - assets/animations/success.flr
    # - assets/images/destination_map_marker.png
    # - assets/images/topup_Payment.jpg
    # - assets/images/driving_pin.png
    # - assets/images/friend1.jpg
    # - assets/images/friend2.jpg
    - assets/map_style.json
    # - assets/images/checked.png
    # - assets/images/loading.png
    # - assets/images/ico_receive_money.png
    # - assets/images/ico_send_money.png

  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #   - family: Schyler
  fonts:
    - family: Bold
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf

    - family: Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: CM Sans Serif
      fonts:
        - asset: assets/fonts/cm_sans_serif_2012.ttf

    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
