name: koompi_hotspot
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.7.8+27

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  app_settings: ^4.1.0
  badges: ^2.0.1
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.3
  data_connection_checker: ^0.3.4
  date_format: ^2.0.2
  easy_localization: ^3.0.0
  file_picker: ^3.0.2+2
  firebase_remote_config: ^0.10.0+3
  flare_flutter: ^3.0.1
  flutter:
    sdk: flutter
  flutter_absolute_path: ^1.0.6
  flutter_form_builder: ^6.0.1
  flutter_image_compress: ^1.0.0
  flutter_launcher_icons: ^0.9.0
  flutter_localizations:
    sdk: flutter
  flutter_map: ^0.13.1
  flutter_map_marker_cluster: ^0.4.0
  flutter_material_pickers: ^3.1.0
  flutter_screenutil: ^0.4.2
  flutter_svg: ^0.22.0
  flutter_webview_plugin: ^0.4.0
  fluttertoast: ^8.0.7
  font_awesome_flutter: ^9.1.0
  geolocator: ^7.3.1
  google_fonts: ^2.1.0
  google_nav_bar: ^2.0.0
  groovin_widgets: ^2.1.0
  http: ^0.13.3
  internet_speed_test: ^1.5.0
  intl_phone_number_input: ^0.7.0+2
  intro_slider: ^2.4.3
  jwt_decoder: ^2.0.1
  latlong2: ^0.8.0
  line_awesome_icons: ^1.0.4+2
  line_icons: ^2.0.1
  linkable: ^2.0.0
  location: ^4.3.0
  multi_image_picker2: ^5.0.2
  onesignal_flutter: ^3.0.0
  package_info: ^2.0.2
  page_transition: ^2.0.2
  path_provider: ^2.0.2
  percent_indicator: ^3.0.1
  permission_handler: ^8.1.4+2
  pin_code_fields: ^7.2.0
  provider: ^5.0.0
  qr_code_scanner: ^0.4.0
  qr_flutter: ^4.0.0
  quick_actions: ^0.6.0+2
  responsive_framework: ^0.1.2
  rflutter_alert: ^2.0.2
  share: ^2.0.4
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0
  syncfusion_flutter_gauges: ^19.1.69
  url_launcher: ^6.0.6
  wifi_connector: ^1.0.2
  wifi_iot: ^0.3.4

flutter_icons:
  image_path: "assets/images/Koompi-WiFi-Icon.png"
  ios: true
  android: true

dev_dependencies:
  flutter_test:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/animations/
    - assets/lang/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #   - family: Schyler
  fonts:
    - family: Bold
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf

    - family: Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: CM Sans Serif
      fonts:
        - asset: assets/fonts/cm_sans_serif_2012.ttf

    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: Poppins-Light
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf

    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
